modLoader="javafml"
loaderVersion="[34,)" #forge version dep
license="GNU Lesser General Public License v3.0"
issueTrackerURL="https://github.com/iChun/TrailMix/issues"

[[mods]]
    modId="trailmix"
    version="${file.jarVersion}" #mandatory
    displayName="Trail Mix"
    displayURL="https://ichun.me/mods/trail-mix/"
    authors="iChun"
    description='''
    This mod adds a single food item, called trail mix. A great snack for any party!
    '''

[[dependencies.trailmix]]
    modId="ichunutil"
    mandatory=true
    versionRange="[10.0.0,11)"
    ordering="NONE"
    side="BOTH"
