modLoader="javafml"
loaderVersion="[31,)" #forge version dep
issueTrackerURL="https://github.com/iChun/TrailMix/issues"

[[mods]]
    modId="trailmix"
    version="${file.jarVersion}" #mandatory
    displayName="Trail Mix"
    displayURL="https://ichun.me/mods/trail-mix/"
    authors="iChun"
    description='''
    This mod adds a single food item, called trail mix. A great snack for any party!
    '''

[[dependencies.trailmix]]
    modId="ichunutil"
    mandatory=true
    versionRange="[8.0.0,9)"
    ordering="NONE"
    side="BOTH"
